# Generated by Django 5.2.7 on 2025-11-10 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_progress'),
    ]

    operations = [
        migrations.AddField(
            model_name='books',
            name='percent_finished',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='books',
            name='total_pages_read',
            field=models.IntegerField(default=0),
        ),
    ]
